version: '3.8'
services:
    redis:
        image: 'redis'
        ports:
          - "6379:6379"
    publisher:
        build:
            context: ./pub
            dockerfile: Dockerfile
        depends_on:
          - "redis"
        image: publisher:latest
    subscriber:
        build:
            context: ./sub
            dockerfile: Dockerfile
        depends_on:
          - "redis"
          - "publisher"
        image: subscriber:latest
